apiVersion: v1
kind: ConfigMap
metadata:
  name: edge-identities
  namespace: default
data:
  values.yaml: |
    e4kdmqtt:
      broker:
        frontend:
          replicas: 2
        backend:
          replicas: 2
          chainCount: 2
      authentication:
        credentials:
          configToml: |
            [onder]
            password = "$argon2id$v=19$m=16,t=2,p=1$MTIzNDU2Nzg$Rm5h90nn/O4Xdj2tcOyl+w"

            [onder.attributes]
            floor = "floor1"
            site = "site1"          
