apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: e4k-helmrelease
  namespace: default
spec:
  releaseName: e4k-dev
  chart:
    spec:
      chart: az-e4k
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: my-repository
        namespace: default
  interval: 30m
  valuesFrom:
  - kind: ConfigMap
    name: edge-identities
