apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: my-repository
  namespace: default
spec:
  type: "oci"
  # The interval at which to check the upstream for updates
  interval: 1m
  # The repository URL, can be a HTTP/S or SSH address
  # url: https://azedgecharts.blob.core.windows.net/helm/
  url: oci://edgecharts.azurecr.io/helm/az-e4k
